[pytest]
base_url = https://www.saucedemo.com/

pythonpath = .

addopts = 
    --browser=chromium 
    ; headed --screenshot=on
;--slowmo=1500
;--tracing=retain-on-failure
    --screenshot=on 
    --html=report.html
    --selfcontained-html
;--video=retain-on-failure
