import re
from playwright.sync_api import Playwright, sync_playwright, expect


def run(playwright: Playwright) -> None:
    browser = playwright.chromium.launch(headless=False)
    context = browser.new_context()
    page = context.new_page()
    page.goto("https://the-internet.herokuapp.com/login")
    page.locator("body").click()
    page.get_by_text("Password", exact=True).click()
    page.get_by_role("textbox", name="Username").click()
    page.get_by_role("textbox", name="Username").fill("tomsmith")
    page.get_by_role("textbox", name="Username").press("Tab")
    page.get_by_role("textbox", name="Password").fill("SuperSecretPassword")
    page.get_by_role("textbox", name="Password").press("Enter")
    page.get_by_role("button", name=" Login").click()
    page.get_by_role("textbox", name="Username").click()
    page.get_by_text("Your password is invalid! × Login Page This is where you can log into the").click()
    page.get_by_role("textbox", name="Username").click()
    page.get_by_role("textbox", name="Username").fill("tomsmith")
    page.get_by_role("textbox", name="Username").press("Tab")
    page.get_by_role("textbox", name="Password").fill("SuperSecrtPassword!")
    page.get_by_role("textbox", name="Password").press("Enter")
    page.get_by_role("button", name=" Login").click()
    page.get_by_text("Your password is invalid! × Login Page This is where you can log into the").click()
    page.get_by_role("textbox", name="Username").click()
    page.get_by_role("textbox", name="Username").fill("tomsmith")
    page.get_by_role("textbox", name="Username").press("Tab")
    page.get_by_role("textbox", name="Password").fill("SuperSecretPassword!")
    page.get_by_role("textbox", name="Password").press("Enter")
    page.get_by_role("button", name=" Login").click()
